/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'typer' at '27/05/18 14:39' with Gradle 3.1
 *
 * @author typer, @date 27/05/18 14:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
